name: template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  mobx:
  flutter_mobx:
  cloud_firestore:
  firebase_core:
  firebase_auth:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  mobx_codegen:
flutter:
  uses-material-design: true
